### ISSUE TITLE
Port install command

### ISSUE THREAD

**Issue by holms** [ansiblebit/macports#6]
I've actually noticed that you're the only role on ansible-galaxy. I found similar role for homebrew which allows to install packages from brew, maybe you'd like to have the same with your role for macports? I'm more macports user, and main reason to use this role would be to install packages from ports. What do you think?

**Comment by holms** [comment]
Ouch my bad :) http://docs.ansible.com/ansible/latest/macports_module.html there's official module!

**Comment by steenzout** [comment]
no problem :)
